# For more information: https://laravel.com/docs/sail
version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./.docker/web/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./web:/app
    depends_on:
      - web_db
  web_db:
    image: mysql:8
    container_name: web_db
    ports:
      - 3308:3306
    volumes:
      - .docker/data/web_db:/var/lib/mysql
    command:
      - "--default-authentication-plugin=mysql_native_password"
      - "--lower_case_table_names=1"
    environment:
      MYSQL_ROOT_PASSWORD: root_pwd
      MYSQL_DATABASE: web_db
      MYSQL_USER: web_user
      MYSQL_PASSWORD: web_pwd


